import { cva } from "class-variance-authority";

export const buttonVariants = cva(
    [
        "inline-flex",
        "items-center",
        "justify-center",
        "gap-2",
        "rounded-xl",
        "font-medium",
        "text-sm",
        "transition-all",
        "duration-200",
        "ease-out",
        "cursor-pointer",
        "select-none",
        "disabled:pointer-events-none",
        "disabled:opacity-50",
        "focus-visible:outline-none",
        "focus-visible:ring-2",
        "focus-visible:ring-primary/25",
    ],
    {
        variants: {
            variant: {
                primary: [
                    "bg-primary",
                    "text-white",
                    "shadow-sm",
                    "hover:bg-primary-hover",
                    "hover:shadow-card",
                    "active:scale-[0.98]",
                ].join(" "),
                secondary: [
                    "bg-secondary",
                    "text-white",
                    "shadow-sm",
                    "hover:bg-secondary-hover",
                    "hover:shadow-card",
                    "active:scale-[0.98]",
                ].join(" "),
                accent: [
                    "bg-accent",
                    "text-white",
                    "shadow-sm",
                    "hover:bg-accent-hover",
                    "hover:shadow-card",
                    "active:scale-[0.98]",
                ].join(" "),
                soft: [
                    "bg-primary-light",
                    "text-primary",
                    "border",
                    "border-primary/15",
                    "hover:bg-primary/10",
                    "active:scale-[0.98]",
                ].join(" "),
                outline: [
                    "bg-surface",
                    "border",
                    "border-border",
                    "text-foreground",
                    "shadow-xs",
                    "hover:border-primary/40",
                    "hover:text-primary",
                    "hover:bg-surface-subtle",
                    "active:scale-[0.98]",
                ].join(" "),
                ghost: [
                    "bg-transparent",
                    "text-foreground-secondary",
                    "hover:text-foreground",
                    "hover:bg-surface-subtle",
                    "active:scale-[0.98]",
                ].join(" "),
                glass: [
                    "bg-surface/85",
                    "backdrop-blur-md",
                    "border",
                    "border-border",
                    "text-foreground",
                    "shadow-xs",
                    "hover:bg-surface",
                    "hover:border-primary/30",
                    "active:scale-[0.98]",
                ].join(" "),
                danger: [
                    "bg-error",
                    "text-white",
                    "shadow-sm",
                ].join(" "),
                success: [
                    "bg-success",
                    "text-white",
                    "shadow-sm",
                ].join(" "),
                warning: [
                    "bg-warning",
                    "text-white",
                    "shadow-sm",
                ].join(" "),
            },
            size: {
                xs: "h-8 px-3 text-xs",
                sm: "h-9 px-4 text-xs font-medium",
                md: "h-11 px-5 text-sm font-medium",
                lg: "h-12 px-7 text-base font-semibold",
            },
        },
        defaultVariants: {
            variant: "primary",
            size: "md",
        },
    }
);